djangoProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from app.views import Login, Registration, Logout, ProductListView, ProductDetailView, ProductCreateView, \
    ProdUpdateView, PurchaseCreate, PurchaseView, ReturnCreateView, AdminReturnView, CancelReturn, AdminAcceptReturn

urlpatterns = [
    path('', ProductListView.as_view(), name='base'),
    path('admin/', admin.site.urls),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('register/', Registration.as_view(), name='registration'),
    path('product/<slug:slug>/', ProductDetailView.as_view(), name='product_item'),
    path('create_product/', ProductCreateView.as_view(), name='create'),
    path('update_product/<slug:slug>/', ProdUpdateView.as_view(), name='update'),
    path('buy/<slug:slug>/', PurchaseCreate.as_view(), name='buy_product'),
    path('purchase/', PurchaseView.as_view(), name='buy_view'),
    path('return/<int:purchase_id>/create', ReturnCreateView.as_view(), name='return'),
    path('su_returns/', AdminReturnView.as_view(), name='admin_return'),
    path('accept_return/<int:pk>', AdminAcceptReturn.as_view(), name='accept_return'),
    path('canc_ret/<int:pk>', CancelReturn.as_view(), name='cancel_return')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.text import slugify


class User(AbstractUser):
    wallet = models.DecimalField(max_digits=10, decimal_places=2, default=12345)
    image = models.ImageField(upload_to='app/images', max_length=100)


class Product(models.Model):
    slug = models.SlugField(max_length=48, unique=True)
    name = models.CharField(max_length=255)
    description = models.TextField( )
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='app/images', max_length=100)
    quantity = models.PositiveIntegerField()

    def save(self, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(**kwargs)

    def __str__(self):
        return self.name


class Purchase(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product')
    prodquan = models.PositiveIntegerField()
    purchase_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.product}-{self.user}-{self.purchase_time}"


class Return(models.Model):
    purchase = models.OneToOneField(Purchase, on_delete=models.CASCADE, related_name='purchase')
    request_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.purchase}-{self.request_time}"

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>My Shop</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'base' %}">My Shop</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collaps navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            {% if request.user.is_superuser %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'create' %}">Add Product</a>
            </li>
            {% endif %}
        </ul>
    </div>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="#"> Your money: ${{ user.wallet }}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'buy_view' %}"> Your purchases </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin_return' %}"> User Returns </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Welcome, {{ user.username }}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'registration' %}">Sign Up</a>
            </li>
            {% endif %}
        </ul>
    </div>
    <div class="w-auto p-3">
        {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>Error: </strong> {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% else %}

        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>Good: </strong> {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endif %}
        {% endfor %}

    </div>
</nav>
<div class="container">
    {% block content %}
    <h1>Products</h1>
    <div class="row">
        {% for product in object_list %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <a href={% url 'product_item' product.slug %}><img src="{{ product.image.url }}"
                                                                   class="rounded mx-auto d-block"
                                                                   style="height: 190px; weight: 190px"
                                                                   alt="{{ item.product.slug }}"></a>
                <div class="card-body">
                    <h5 class="card-title">{{ product.name }}</h5>
                    <p class="card-text">{{ product.description }}</p>
                    <p class="card-text">Price: ${{ product.price }}</p>
                    <p class="card-text">Amount: {{ product.quantity }}</p>
                </div>

                <a href={% url 'product_item' product.slug %} class="btn btn-outline-primary" >Show</a>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-primary">previous</a>
        {% endif %}
        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-primary">next</a>
        {% endif %}
    </span>
    </div>
    {% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

templates/create_product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container-sm">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" value="Save" class="btn btn-outline-success">Add</button>
    </form>
</div>
{% endblock %}

templates/log-in.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h2>Log in</h2>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Login">
    </form>
{% endblock %}

templates/modal_view_product_image.html
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#imageModal" data-border="none"
        data-outline="none">
    <img src="{{ product.image.url }}" class="rounded mx-auto d-block" style="height: 500px; weight: 500px"
         alt="{{ product.slug }}">
</button>
<div class="modal fade" id="imageModal" tabindex="-1" role="dialog" aria-labelledby="imageModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <img src="{{ product.image.url }}" class="img-fluid" alt="{{ product.slug }}">
            </div>
        </div>
    </div>
</div>

templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="d-flex align-items-start mb-3" style="margin-top: 15px; margin-left: 45px;">
    {% include 'modal_view_product_image.html' %}
    <div class="card-body" style="margin-left: 45px;">
        <h5 class="card-title">{{ product.title }}</h5>
        <p class="card-text">{{ product.description }}</p>
        <p class="card-text">Price: {{ product.price }}$</p>
        <p class="card-text"><small class="text-body-secondary">Amount: {{ product.quantity }} </small></p>
    </div>
    <div class="card-body">
        {% if request.user.is_superuser %}
        <a href={% url "update" product.slug %} class="btn btn-outline-secondary">Update</a>
        {% endif %}
        {% if request.user.is_authenticated %}
        <form method="post" action="{% url 'buy_product' product.slug %}">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-primary">Buy</button>
        </form>
        {% endif %}
    </div>
</div>
<div class="card-body">
    <a href={% url "base" %} class="btn btn-danger">Back</a>
</div>
{% endblock %}

templates/registration.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<form method="post" >
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Registration">
</form>
<a class="nav-link" href={% url 'login' %}>Login</a>
{% endblock %}

templates/return_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Returns:</h1>
<br>
{% for return in return_list %}
<div class="form-control form-control-lg">
    Name: {{ return.purchase.product.name }} User: {{ return.purchase.user }}
    Amount: {{ return.purchase.prodquan }}

    <form name="return-form" method="post" action="{% url 'accept_return' return.purchase.id %}">
        {% csrf_token %}

        <input type="hidden" name="accept" value="{{ return.id }}">
        <button class="btn btn-danger" type="submit">Accept</button>
    </form>
    <br>
    <form name="return-form" method="post" action="{% url 'cancel_return' return.purchase.id %}">
        {% csrf_token %}

        <input type="hidden" name="accept" value="{{ return.id }}">
        <button class="btn btn-danger" type="submit">Cancel</button>
    </form>
</div>
{% endfor %}
{% endblock %}

templates/update_product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container-sm">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" value="Save" class="btn btn-outline-success">Update</button>
    </form>
</div>
{% endblock %}

templates/user_purchases.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Your Purchases:</h1>
<br>

{% for purchase in purchase_list %}

<form class="form-control form-control-lg" method="post">{% csrf_token %}
    {{ purchase.id }} {{ purchase.product.name }} Amount: {{ purchase.prodquan }} Purchase time: {{ purchase.purchase_time }}
</form>
<form name="return-form" method="post" action="{% url 'return' purchase.id %}">
    {% csrf_token %}
    <input type="hidden" name="purchase_id" value="{{ purchase.id }}">
    <button class="btn btn-outline-danger" type="submit">Return</button>
</form>
{% endfor %}
{% endblock %}